### ISSUE TITLE
Google Code is down

### ISSUE THREAD

**Issue by alexandre-mbm** [rkapsi/patricia-trie#13]
I look for examples and instructions.

**Comment by alexandre-mbm** [comment]
- [x] https://web.archive.org/web/20150512181516/http://code.google.com/p/patricia-trie/wiki/Examples

**Comment by alexandre-mbm** [comment]
https://github.com/rkapsi/patricia-trie/wiki/Simple-Example

**Comment by rkapsi** [comment]
:tada: thx!

**Comment by alexandre-mbm** [comment]
Now I am looking the code contributed at target projects.

**Comment by alexandre-mbm** [comment]
- [ ] The project **google-collections** was [renamed](https://code.google.com/archive/p/google-collections/issues/5) to guava and its issue is at google/guava#10
- [x] The project **[commons-collections]** includes the package [org.apache.commons.collections4.trie]

[commons-collections]: http://commons.apache.org/proper/commons-collections/
[org.apache.commons.collections4.trie]: http://commons.apache.org/proper/commons-collections/javadocs/api-release/org/apache/commons/collections4/trie/package-summary.html
