### ISSUE TITLE
Support for variable length byte array keys

### ISSUE THREAD

**Issue by sparcs** [rkapsi/patricia-trie#3]
This is more a question than an issue.

The current implementation of ByteArrayKeyAnalyser is written for fixed length keys. Is there any way we could adapt it to use variable length byte arrays without too much of a change? 

The reason I'm asking is that, a variable length byte array key analyser would most likely perform better than string key analyser, for strings that are primarily made up of the Latin character set.

**Comment by rkapsi** [comment]
Hey,

yea - you're right. I've added a ByteArrayKeyAnalyzer for variable length keys.

https://github.com/rkapsi/patricia-trie/commit/d8915a3136833d471c39f4c7b765d1c3c10746d8

And I think I will add a StringKeyAnalyzer that will ignore the upper 8 bits of each char.

**Comment by sparcs** [comment]
hi,

Thanks for the update and sorry for my delayed response. 

By the time you got back, I'd written a byte array string analyser myself and tested it. Just thought I'd share some info about my tests as it might be of interest to you. The data contains UTF-8 strings as keys, about 7 million distinct ones. Each key's value is mapped to a list of longs. The length of the key strings were anywhere between 6 to 200 characters. The maximum density of key length being around 20-30 characters and a long tail distribution thereafter.

With the byte array approach I didn't find any significant improvement in performance for String search. The byte array index was smaller when written to disk but not by a very large margin. The runtime wasn't different either and sometimes exceeded the original implementation. I thought this was something to do with the bitwise checking and Java's byte handling in memory. Java operates on bytes as integers, so there is no real saving in the primary memory occupied by the program. I changed isBitSet and bitIndex methods to operate on ints rather than bytes. Still almost similar performance as operating on bits in bytes. 

I'm not sure if what I've said is clear enough. In short, I found your original String Analyser implementation good enough without all the byte transformation :)

You could run more tests to ascertain it for sure.

cheers!
