### ISSUE TITLE
Functional issue on retrieve string

### ISSUE THREAD

**Issue by ColinBinWang** [rkapsi/patricia-trie#4]
Here is a simple code to produce the issue:

import java.io.IOException;
import org.ardverk.collection.PatriciaTrie;
import org.ardverk.collection.StringKeyAnalyzer;

public class Main {

```
public static void main(String[] args) throws IOException {
    PatriciaTrie<String, String> trie =
        new PatriciaTrie<String, String>(StringKeyAnalyzer.CHAR);
    trie.put("10010", "value1");
    trie.put("1001", "value2");
    String out = trie.selectKey("100110000");
    System.out.println(out); // out is 10010, rather than 1001 as expected.
}
```

}

**Comment by rkapsi** [comment]
Hey,

The problem is that `100110000` is neither a prefix of `1001` nor `10010` and `select()` returns meaningful results only if you query by prefix such as `100`. The fact that it returns always something is just a property of Tries and the final check is left up to the user.

**Comment by ColinBinWang** [comment]
It is not a good practice to store the binary string as the representation of IPv4 CIDR.
In our case, we want to store IPv4 CIDR ranges in the trie, and test if some specified IP falls into the ranges. In another word, we want to check if the trie stores the prefix of IP.

StringKeyAnalyzer is not a proper way in our case.
        PatriciaTrie<String, String> trie = new PatriciaTrie<String, String>(StringKeyAnalyzer.CHAR);
        trie.put("1001", "value1");
        trie.put("10010", "value2");
        trie.put("10011", "value3");
        System.out.println(trie);
The output is:
Trie[3]={
  Entry(key=1001 [10], value=value1, parent=ROOT, left=ROOT, right=10010 [74], predecessor=10010 [74])
  Entry(key=10010 [74], value=value2, parent=1001 [10], left=1001 [10], right=10011 [79], predecessor=10011 [79])
  Entry(key=10011 [79], value=value3, parent=10010 [74], left=10010 [74], right=10011 [79], predecessor=10011 [79])
}
The trie structure is: 
"1001" ---(right child)-> "10010" ---(right child)-> "10011".
Not our expected:
"1001" ---(left child)-> "10010"
"1001" ---(right child)-> "10011"

So we have decided to use IntegerKeyAnalyzer instead.
Hope it will works.

Thanks,
Bin Wang
