### ISSUE TITLE
Improve space efficiency by avoiding key storage?

### ISSUE THREAD

**Issue by acruise** [rkapsi/patricia-trie#6]
Hi there,

One of the rationales for a PATRICIA Trie is that it should be space-efficient.  However, TrieEntry[K,V] <: BasicEntry[K,V] and BasicEntry retains the key in a field, so overall memory usage ends up being higher than for j.u.HashMap.  Would it make sense to consider an alternative implementation that doesn't retain keys, but rather reconstructs them from path information on-demand?  

Thanks!

**Comment by rkapsi** [comment]
You can't construct the key from the path. Take two keys, one key is Shakespeare's Hamlet and the other is Mac Beth. These will be simply two Nodes in a PATRICIA Trie. It might be a different story for other types of Tries but the runtime complexities involved are significant.

You can get away with removing the key if you don't care about the Map<K, V> functionality. It's perfectly fine for e.g. IP-Routing. 

Check out my other simple-patricia-trie project that is more like a toolkit for custom implementations. The goal of this project was to provide an implementation that plugs into Java's Collections framework and I value speed over memory.
